services:
  mongo:
    image: mongo
    container_name: db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    networks:
      - deep-origin-network

  backend:
    build: ./backend
    container_name: backend
    restart: always
    ports:
      - "3010:3000"
    environment:
      - MONGODB_URL=mongodb://db:27017/deep-origin?retryWrites=true
    depends_on:
      - mongo
    networks:
      - deep-origin-network

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    ports:
      - "3020:5173"
    networks:
      - deep-origin-network

networks:
  deep-origin-network:
    driver: bridge
